version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: sample_app
    restart: unless-stopped
    #env_file: .env
    environment:
      - NODE_ENV=test
    ports:
      - "3000:3000"
    deploy:
     replicas: 4
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s

  proxy:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      image: nginx_proxy
      ports:
        - 8070:8070
      depends_on:
        - nodeapp
      deploy:
        placement:
          constraints: [node.role == manager]
      depends_on:
        - nodejs